### ISSUE TITLE
PixelFormat

### ISSUE THREAD

**Issue by VerliererK** [bibigone/AstraDotNetDemo#2]
Hi,

Thanks for your work!
I have try this demo, and find a issue,
the Astra.PixelFormat is RGB888, and in BufferOfT.cs the WriteableBitmap's PixelFormats is Bgr24.
Is it correct? Not Rgb24?

**Comment by bibigone** [comment]
Hello,

This is correct because WPF `PixelFormats.Bgr24` corresponds to GDI+ `PixelFormat.Format24bppRgb`. You can find more details here: https://stackoverflow.com/questions/5106505/converting-gdi-pixelformat-to-wpf-pixelformat

**Comment by VerliererK** [comment]
Thanks for your reply!

I used Astra Pro.
Here is cpature:
PixelFormats.Bgr24 : https://i.imgur.com/atZ7Usz.png
![image](https://user-images.githubusercontent.com/13897980/36652937-eea8426c-1aec-11e8-8f05-67053e7046c7.png)

PixelFormats.Rgb24 : https://i.imgur.com/Sbgh9zq.png
![image](https://user-images.githubusercontent.com/13897980/36652932-e92c0378-1aec-11e8-98cc-79f339634e6b.png)

And using SimpleColorViewer-SFML.exe from AstraSDK-v2.0.8-beta2
https://i.imgur.com/8nFukkO.png
![image](https://user-images.githubusercontent.com/13897980/36652949-04f45a24-1aed-11e8-92f7-d6836046c54a.png)

The demo of SDK is same as PixelFormats.Rgb24.
Is there something wrong?

**Comment by bibigone** [comment]
Hello @VerliererK,

Thank you for these great details. And sorry for so long silence from my side.

You're totally right. I've just fixed this issue (see commit 44fe027).
