### ISSUE TITLE
BodyTracking not working

### ISSUE THREAD

**Issue by ghost** [bibigone/AstraDotNetDemo#5]
Hi,

I have tried the current example with Astra Pro, but somehow the BodyTracking does not work.

`streamReader.TryOpenFrame(10, out var frame)`
in SensorViewModels.cs line 309 is never true.

May you check if it works for you?

Thanks in advance.

**Comment by bibigone** [comment]
Hello,

this is because free trial period of BodyTracking has been expired. I switched to new version of AstraSDK - 2.0.9 beta3d and this version has new trial period. That is, now body tracking should work. See commit 1aaa662e0eb8f34a6f946b5b451dbab0d217a4ae
