### ISSUE TITLE
Can I use OpenCV inside this wrapper?

### ISSUE THREAD

**Issue by pkr97** [bibigone/AstraDotNetDemo#7]
Hi, It's good to have a working C# wrapper.

I would like to know if there is a way to use OpenCV inside this wrapper.

I need OpenCV for some image processing stuff.

Waiting for a valuable feedback.

Thanks..

**Comment by bibigone** [comment]
Hello pkr97,

This particular wrapper has only API for Orbbec sensors management. If you're going to use OpenCV in C# then you have to use one of .Net-wrappers for OpenCV in addition: https://qiita.com/hengsokvisal/items/5deaa38441b1a740335a

Best
